#!/usr/bin/env python3
import json

# Translations for all languages
translations = {
    "de": {  # German
        "order": "Bestellung",
        "delivery": {
            "dashboard": "Lieferungs-Dashboard",
            "availableOrders": "Verfügbare Bestellungen",
            "myDeliveries": "Meine Lieferungen",
            "earnings": "Einnahmen",
            "history": "Verlauf",
            "accept": "Annehmen",
            "decline": "Ablehnen",
            "pickup": "Abholen",
            "deliver": "Liefern",
            "delivered": "Geliefert",
            "myOrders": "Meine Bestellungen",
            "orders": "Bestellungen",
            "active": "Aktiv",
            "all": "Alle",
            "seeAll": "Alle anzeigen",
            "welcomeBack": "Willkommen zurück",
            "rider": "Fahrer",
            "happeningToday": "Hier ist, was heute mit Ihren Lieferungen passiert.",
            "todaysDeliveries": "Heutige Lieferungen",
            "activeOrders": "Aktive Bestellungen",
            "pending": "Ausstehend",
            "totalOrders": "Gesamtbestellungen",
            "pendingOrders": "Ausstehende Bestellungen",
            "noPendingOrders": "Keine ausstehenden Bestellungen",
            "newOrdersWillAppear": "Neue Bestellungen erscheinen hier",
            "noOrdersFound": "Keine Bestellungen gefunden",
            "noPendingDeliveryOrders": "Derzeit keine ausstehenden Lieferbestellungen",
            "noActiveDeliveries": "Keine aktiven Lieferungen",
            "noOrdersYet": "Noch keine Bestellungen",
            "orderAcceptedSuccessfully": "Bestellung erfolgreich angenommen!",
            "failedToAcceptOrder": "Bestellung konnte nicht angenommen werden",
            "declineOrder": "Bestellung ablehnen",
            "confirmDeclineOrder": "Möchten Sie die Bestellung wirklich ablehnen",
            "orderDeclined": "Bestellung abgelehnt",
            "failedToDeclineOrder": "Bestellung konnte nicht abgelehnt werden",
            "orderNumber": "Bestellung #",
            "items": "Artikel",
            "customer": "Kunde",
            "deliveryAddress": "Lieferadresse",
            "distance": "Entfernung",
            "deliveryFee": "Liefergebühr",
            "deliveryZones": "Lieferzonen",
            "errorLoadingOrders": "Fehler beim Laden der Bestellungen",
            "orderSettings": "Bestelleinstellungen",
            "autoAcceptOrders": "Bestellungen automatisch annehmen",
            "autoAcceptOrdersDesc": "Eingehende Bestellungen automatisch annehmen",
            "maxConcurrentOrders": "Max. gleichzeitige Bestellungen",
            "maxConcurrentOrdersDesc": "Maximale Anzahl gleichzeitig zu bearbeitender Bestellungen",
            "notificationSettings": "Benachrichtigungseinstellungen",
            "pushNotifications": "Push-Benachrichtigungen",
            "pushNotificationsDesc": "Benachrichtigungen für neue Bestellungen erhalten",
            "sound": "Ton",
            "soundDesc": "Ton für neue Bestellungen abspielen",
            "vibration": "Vibration",
            "vibrationDesc": "Für neue Bestellungen vibrieren",
            "zones": "Lieferzonen",
            "totalZones": "Gesamtzonen",
            "activeZones": "Aktive Zonen",
            "preferred": "Bevorzugt",
            "noZonesAvailable": "Keine Lieferzonen verfügbar",
            "zonesWillAppearHere": "Ihre zugewiesenen Lieferzonen erscheinen hier",
            "zoneName": "Zonenname",
            "coverage": "Abdeckung",
            "status": "Status",
            "deliveryProfile": "Lieferprofil",
            "personalInformation": "Persönliche Informationen",
            "firstName": "Vorname",
            "lastName": "Nachname",
            "phone": "Telefon",
            "email": "E-Mail",
            "vehicleInformation": "Fahrzeuginformationen",
            "vehicleType": "Fahrzeugtyp",
            "vehicleModel": "Fahrzeugmodell",
            "vehicleNumber": "Fahrzeugnummer",
            "licenseNumber": "Führerscheinnummer",
            "accountStatus": "Kontostatus",
            "verified": "Verifiziert",
            "unverified": "Nicht verifiziert",
            "updateProfile": "Profil aktualisieren",
            "totalEarnings": "Gesamteinnahmen",
            "todayEarnings": "Heutige Einnahmen",
            "weekEarnings": "Diese Woche",
            "monthEarnings": "Dieser Monat",
            "noEarningsData": "Keine Einnahmendaten",
            "earningsBreakdown": "Einnahmenaufschlüsselung",
            "statistics": "Statistiken",
            "completedDeliveries": "Abgeschlossene Lieferungen",
            "averagePerDelivery": "Durchschnitt pro Lieferung",
            "tips": "Trinkgelder",
            "bonuses": "Boni",
            "earningsHistory": "Einnahmenverlauf",
            "date": "Datum",
            "amount": "Betrag",
            "deliveries": "Lieferungen",
            "deliveryHistory": "Lieferverlauf",
            "completed": "Abgeschlossen",
            "cancelled": "Storniert",
            "noHistoryAvailable": "Kein Lieferverlauf verfügbar",
            "historyWillAppearHere": "Ihre abgeschlossenen Lieferungen erscheinen hier",
            "completedOn": "Abgeschlossen am",
            "cancelledOn": "Storniert am",
            "deliveryTime": "Lieferzeit",
            "rating": "Bewertung",
            "viewDetails": "Details anzeigen",
            "orderDetails": "Bestelldetails",
            "customerInformation": "Kundeninformationen",
            "name": "Name",
            "pickupAddress": "Abholadresse",
            "orderItems": "Bestellartikel",
            "paymentSummary": "Zahlungsübersicht",
            "subtotal": "Zwischensumme",
            "total": "Gesamt",
            "paymentMethod": "Zahlungsmethode",
            "cash": "Bargeld",
            "card": "Karte",
            "online": "Online",
            "myReviews": "Meine Bewertungen",
            "averageRating": "Durchschnittsbewertung",
            "reviews": "Bewertungen",
            "noReviewsYet": "Noch keine Bewertungen",
            "reviewsWillAppearHere": "Kundenbewertungen erscheinen hier",
            "ratedYou": "hat Sie bewertet",
            "stars": "Sterne",
            "reviewFrom": "Bewertung von",
            "workingHours": "Arbeitszeiten",
            "startTime": "Startzeit",
            "endTime": "Endzeit",
            "deliveryPartner": "Lieferpartner",
            "errorLoadingEarnings": "Fehler beim Laden der Einnahmen",
            "today": "Heute",
            "thisWeek": "Diese Woche",
            "thisMonth": "Dieser Monat",
            "allTime": "Alle Zeit",
            "totalDeliveries": "Gesamtlieferungen",
            "ratings": "Bewertungen",
            "withdrawFunds": "Geld abheben",
            "availableBalance": "Verfügbares Guthaben",
            "withdrawalAmount": "Abhebungsbetrag",
            "max": "Max",
            "number": "Nummer",
            "accountNameOptional": "Kontoname (Optional)",
            "bankName": "Bankname",
            "accountNumber": "Kontonummer",
            "accountHolderName": "Kontoinhaber",
            "cashWithdrawalInfo": "Bargeldabhebungen werden Ihnen vom Administrator übergeben. Bitte besuchen Sie das Büro zur Abholung.",
            "withdraw": "Abheben",
            "pleaseEnterValidAmount": "Bitte geben Sie einen gültigen Betrag ein",
            "insufficientBalance": "Unzureichendes Guthaben. Verfügbar:",
            "pleaseEnterMobileNumber": "Bitte geben Sie Ihre Mobilnummer ein",
            "pleaseEnterBankDetails": "Bitte geben Sie die Bankdaten ein",
            "withdrawalRequestSuccess": "Abhebungsanfrage erfolgreich eingereicht!",
            "failedToSubmitWithdrawal": "Fehler beim Einreichen der Abhebung",
            "errorLoadingHistory": "Fehler beim Laden des Verlaufs",
            "earned": "Verdient",
            "todayAt": "Heute,",
            "yesterdayAt": "Gestern,",
            "daysAgo": "Tage her",
            "since": "Seit",
            "bicycle": "Fahrrad",
            "motorcycle": "Motorrad",
            "scooter": "Roller",
            "car": "Auto",
            "van": "Transporter",
            "idType": "Ausweistyp",
            "nationalId": "Personalausweis",
            "passport": "Reisepass",
            "drivingLicense": "Führerschein",
            "bankDetails": "Bankdaten",
            "pleaseEnter": "Bitte eingeben",
            "profileUpdatedSuccessfully": "Profil erfolgreich aktualisiert"
        },
        "settings": {
            "settings": "Einstellungen",
            "language": "Sprache",
            "selectLanguage": "Sprache auswählen",
            "theme": "Design",
            "light": "Hell",
            "dark": "Dunkel",
            "system": "System",
            "notifications": "Benachrichtigungen",
            "pushNotifications": "Push-Benachrichtigungen",
            "emailNotifications": "E-Mail-Benachrichtigungen",
            "twoFactorAuth": "Zwei-Faktor-Authentifizierung",
            "orderUpdates": "Bestellaktualisierungen",
            "promotions": "Werbeaktionen",
            "appearance": "Erscheinungsbild",
            "refreshTheme": "Design & Schrift aktualisieren",
            "syncDesign": "Mit neuestem Design vom Server synchronisieren",
            "selectTheme": "Design auswählen",
            "privacy": "Datenschutz",
            "privacyPolicy": "Datenschutzrichtlinie",
            "downloadData": "Meine Daten herunterladen",
            "dataExportEmail": "Datenexport wird an Ihre E-Mail gesendet",
            "terms": "Geschäftsbedingungen",
            "about": "Über",
            "help": "Hilfe & Support",
            "appVersion": "App-Version",
            "dangerZone": "Gefahrenzone",
            "deleteAccount": "Konto löschen",
            "deleteAccountWarning": "Möchten Sie Ihr Konto wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.",
            "accountDeletionRequested": "Kontolöschung angefordert",
            "themeRefreshed": "Design und Schrift erfolgreich aktualisiert!",
            "logout": "Abmelden",
            "confirmLogout": "Möchten Sie sich wirklich abmelden?",
            "languageChanged": "Sprache erfolgreich geändert",
            "settingsSaved": "Einstellungen erfolgreich gespeichert"
        }
    }
}

print("Translation data prepared for German")
print(json.dumps(translations["de"]["delivery"], indent=2, ensure_ascii=False)[:500])
